"""
Build #16 — Assemble a 28-second App Store "App Preview" video from the
banner slides generated by generate_marketing_assets.py.

Output: /app/store/marketing/app-preview-15-30s.mp4 (1080x1920 H.264)

Apple App Preview requirements:
  - 15-30 seconds
  - MP4 / MOV / M4V, H.264, AAC if audio
  - Resolution: 1080x1920 (iPhone 6.5"+), 1242x2208 (5.5"), or matching screenshot size
  - Optional audio; we go silent for honesty (no exaggerated music hype)
"""
import subprocess
import sys
from pathlib import Path
from PIL import Image

ROOT = Path("/app/store/marketing")
TARGET = ROOT / "app-preview-15-30s.mp4"

# Source slides — order = playback order.
SLIDES = [
    ROOT / "banner-hero.png",
    ROOT / "banner-feature-mine.png",
    ROOT / "banner-feature-yield.png",
    ROOT / "banner-feature-support.png",
    ROOT / "banner-cta.png",
]

# Each slide held for this many seconds (5 slides x 5.6s = 28s ✓ within 15-30s)
HOLD_SECONDS = 5.6
TARGET_W, TARGET_H = 1080, 1920


def resize_to_portrait(src: Path, dst: Path):
    """Resize/letterbox a 16:9 slide onto a 1080x1920 portrait canvas with
    matte black bars so nothing is cropped."""
    img = Image.open(src).convert("RGB")
    canvas = Image.new("RGB", (TARGET_W, TARGET_H), color=(11, 14, 20))  # #0B0E14
    # Scale to fit width preserving aspect.
    w, h = img.size
    new_w = TARGET_W
    new_h = int(h * (new_w / w))
    img = img.resize((new_w, new_h), Image.LANCZOS)
    y = (TARGET_H - new_h) // 2
    canvas.paste(img, (0, y))
    canvas.save(dst, "PNG", optimize=True)


def main() -> int:
    if not all(p.exists() for p in SLIDES):
        missing = [str(p) for p in SLIDES if not p.exists()]
        print(f"ERROR: missing source slides: {missing}")
        return 1

    tmp_dir = ROOT / "_video_tmp"
    tmp_dir.mkdir(parents=True, exist_ok=True)

    # 1) Resize every slide to 1080x1920 portrait.
    portrait_slides = []
    for i, s in enumerate(SLIDES):
        out = tmp_dir / f"slide-{i:02d}.png"
        resize_to_portrait(s, out)
        portrait_slides.append(out)
        print(f"  ✓ portrait {out.name}")

    # 2) Build an ffmpeg concat file describing the timeline.
    concat_file = tmp_dir / "concat.txt"
    with concat_file.open("w") as f:
        for p in portrait_slides:
            f.write(f"file '{p.resolve()}'\n")
            f.write(f"duration {HOLD_SECONDS}\n")
        # ffmpeg concat demuxer needs the last file repeated without duration
        f.write(f"file '{portrait_slides[-1].resolve()}'\n")

    # 3) Encode.
    cmd = [
        "ffmpeg",
        "-y",
        "-f", "concat",
        "-safe", "0",
        "-i", str(concat_file),
        "-vf", "fps=30,format=yuv420p,scale=1080:1920:flags=lanczos",
        "-c:v", "libx264",
        "-pix_fmt", "yuv420p",
        "-preset", "medium",
        "-crf", "20",
        "-movflags", "+faststart",
        str(TARGET),
    ]
    print("  → ffmpeg encoding …")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        print("ffmpeg failed:")
        print(result.stderr[-1500:])
        return 1

    size_mb = TARGET.stat().st_size / 1024 / 1024
    # Probe duration.
    probe = subprocess.run(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(TARGET)],
        capture_output=True, text=True,
    )
    duration = float(probe.stdout.strip() or "0")
    print(f"\n✓ Promo video ready: {TARGET}")
    print(f"  Size:     {size_mb:.2f} MB")
    print(f"  Duration: {duration:.2f}s  (Apple accepts 15-30s)")
    print(f"  Resolution: {TARGET_W}x{TARGET_H} portrait")
    return 0


if __name__ == "__main__":
    sys.exit(main())
